### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by andreluizbarbieri** [LaurentBerger/wxOpenCV#2]
I was try building in Windows... No easy... after build all dependency, I can't configure PLplot_DIR and it show "PLplot_DIR-NOTFOUND" even with PLplot compiled and all .dll files compiled.
Vtk_dir ok
Osg_dir ok
Wxwidgets_dir ok

But I still get "PLplot_DIR-NOTFOUND" even set PLplot_DIR to C:\PLplot\build or C:\PLplot
after click in Configure button, Cmake not found only this dependency

**Comment by andreluizbarbieri** [comment]
I think that I fixed:
"
#find_package(PLplot  REQUIRED)
SET("PLplot_DIR" "C:/PLplot/build")
"

**Comment by andreluizbarbieri** [comment]
Now building...

But with errors:

> `MSVC\14.11.25503\include\sstream(28): error C2061: syntax error: identifier 'openmode'`

> `MSVC\14.11.25503\include\sstream(225): error C2061: syntax error: identifier 'seekdir'`

**Comment by LaurentBerger** [comment]
About you can solve problem  using SET("PLplot_DIR" "C:/PLplot/build") but I use
g:/lib/install/plplot/lib/cmake/plplot and plplot is installed in g:/lib/install.

I use vs 2015 Win64 to build wxOpenCV. You have Vs2017. Do you use use  Visual Studio 15 2017 Win64 generator in cmake?

**Comment by andreluizbarbieri** [comment]
I think that errors 
> `MSVC\14.11.25503\include\sstream(28): error C2061: syntax error: identifier 'openmode'`

> `MSVC\14.11.25503\include\sstream(225): error C2061: syntax error: identifier 'seekdir'`

I fixed , when I Uncheck (in CmakeGui) the variable BUILD_SHARED_LIBS ... that I had forgot it! Because in all dependency I uncheck shared_libs but in PLplot  forgot...

**Comment by andreluizbarbieri** [comment]
But now I have others errors:

> `1>CaptureInfo3D.cpp`
`1>C:\Users\andre\Source\repos\OpenSceneGraph\include\OpenThreads/Atomic(110): error C3861: '__sync_add_and_fetch': identificador não encontrado
1>C:\Users\andre\Source\repos\OpenSceneGraph\include\OpenThreads/Atomic(127): error C3861: '__sync_sub_and_fetch': identificador não encontrado
1>C:\Users\andre\Source\repos\OpenSceneGraph\include\OpenThreads/Atomic(144): error C3861: '__sync_fetch_and_and': identificador não encontrado
1>C:\Users\andre\Source\repos\OpenSceneGraph\include\OpenThreads/Atomic(163): error C3861: '__sync_fetch_and_or': identificador não encontrado
1>C:\Users\andre\Source\repos\OpenSceneGraph\include\OpenThreads/Atomic(182): error C3861: '__sync_fetch_and_xor': identificador não encontrado
1>C:\Users\andre\Source\repos\OpenSceneGraph\include\OpenThreads/Atomic(203): error C3861: '__sync_lock_test_and_set': identificador não encontrado
1>C:\Users\andre\Source\repos\OpenSceneGraph\include\OpenThreads/Atomic(224): error C3861: '__sync_synchronize': identificador não encontrado
1>C:\Users\andre\Source\repos\OpenSceneGraph\include\OpenThreads/Atomic(244): error C3861: '__sync_bool_compare_and_swap': identificador não encontrado
1>C:\Users\andre\Source\repos\OpenSceneGraph\include\OpenThreads/Atomic(267): error C3861: '__sync_synchronize': identificador não encontrado`

**Comment by LaurentBerger** [comment]
Which is openscenegraph version?

**Comment by andreluizbarbieri** [comment]
last Stable version of OSG.  "OpenSceneGraph 3.4.1"

In Cmake-Gui for this OSG, I found only OPENTHREADS_ATOMIC_USE_MUTEX (unchecked)

**Comment by LaurentBerger** [comment]
You should install openscenegraph (select install project in VS2017)

**Comment by andreluizbarbieri** [comment]
I'm building OSG again with VS2017 (early I had built with Mingw)...

**Comment by LaurentBerger** [comment]
If you have already build osg with vs2017 then just select install project for debug and release version

**Comment by andreluizbarbieri** [comment]
But ALL_BUILD project should not build install project, or no?

**Comment by LaurentBerger** [comment]
No install project is specific you have to select it.

**Comment by andreluizbarbieri** [comment]
after build "ALL_BUILD" of OSG I get in wxOpencv LINK errors:

> `2>ZoneImage.obj : error LNK2001: símbolos externos indefinidos "__declspec(dllimport) public: unsigned int __thiscall OpenThreads::Atomic::operator++(void)" (__imp_??EAtomic@OpenThreads@@QAEIXZ)
2>osgviewerWX.obj : error LNK2001: símbolos externos indefinidos "__declspec(dllimport) public: unsigned int __thiscall OpenThreads::Atomic::operator++(void)" (__imp_??EAtomic@OpenThreads@@QAEIXZ)
2>CaptureInfo3D.obj : error LNK2001: símbolos externos indefinidos "__declspec(dllimport) public: unsigned int __thiscall OpenThreads::Atomic::operator++(void)" (__imp_??EAtomic@OpenThreads@@QAEIXZ)
2>Fenetre3D.obj : error LNK2001: símbolos externos indefinidos "__declspec(dllimport) public: unsigned int __thiscall OpenThreads::Atomic::operator++(void)" (__imp_??EAtomic@OpenThreads@@QAEIXZ)
2>FenetreGraphiqueWX.obj : error LNK2001: símbolos externos indefinidos "__declspec(dllimport) public: unsigned int __thiscall OpenThreads::Atomic::operator++(void)" (__imp_??EAtomic@OpenThreads@@QAEIXZ)
2>NanoSurface.obj : error LNK2001: símbolos externos indefinidos "__declspec(dllimport) public: unsigned int __thiscall OpenThreads::Atomic::operator++(void)" (__imp_??EAtomic@OpenThreads@@QAEIXZ)
2>ZoneImage.obj : error LNK2001: símbolos externos indefinidos "__declspec(dllimport) public: unsigned int __thiscall OpenThreads::Atomic::operator--(void)" (__imp_??FAtomic@OpenThreads@@QAEIXZ)
2>osgviewerWX.obj : error LNK2001: símbolos externos indefinidos "__declspec(dllimport) public: unsigned int __thiscall OpenThreads::Atomic::operator--(void)" (__imp_??FAtomic@OpenThreads@@QAEIXZ)
2>CaptureInfo3D.obj : error LNK2001: símbolos externos indefinidos "__declspec(dllimport) public: unsigned int __thiscall OpenThreads::Atomic::operator--(void)" (__imp_??FAtomic@OpenThreads@@QAEIXZ)
2>Fenetre3D.obj : error LNK2001: símbolos externos indefinidos "__declspec(dllimport) public: unsigned int __thiscall OpenThreads::Atomic::operator--(void)" (__imp_??FAtomic@OpenThreads@@QAEIXZ)
2>FenetreGraphiqueWX.obj : error LNK2001: símbolos externos indefinidos "__declspec(dllimport) public: unsigned int __thiscall OpenThreads::Atomic::operator--(void)" (__imp_??FAtomic@OpenThreads@@QAEIXZ)
2>NanoSurface.obj : error LNK2001: símbolos externos indefinidos "__declspec(dllimport) public: unsigned int __thiscall OpenThreads::Atomic::operator--(void)" (__imp_??FAtomic@OpenThreads@@QAEIXZ)
2>CaptureInfo3D.obj : error LNK2019: símbolo externo indefinido "public: __thiscall osg::Referenced::Referenced(void)"`

Then I'm re-building "INSTALL" project of OSG

**Comment by andreluizbarbieri** [comment]
Which Input files for Linker I need to config? 
I think these above errors are because that 'files'.lib in the Input box of Linker of VS isn't configured...

**Comment by andreluizbarbieri** [comment]
I add all files with ".lib" of OSG and PLplot. Then now I get only few errors of LINKing (less errors now) like these below, I don't know which library I need to set in Input box of Linker:

> `Fenetre3D.obj : error LNK2001: símbolos externos indefinidos "public: class osg::Node * __thiscall osgViewer::Scene::getSceneData(void)"`

> `ImInCVOperation.obj : error LNK2019: símbolo externo indefinido "struct cv::Ptr<class cv::bgsegm::BackgroundSubtractorMOG>`

how can I build this "bgsegm" module if it not coming with "stock opencv solution" but only in opencv-Contrib? ---fixed: Just put module folder in stock module folder and Cmake again...
_bgsegm_ built but the module _optflow_ no build... and wxOpencv need of optflow___.lib

> `C:\opencv-3.3.0\modules\optflow\src\simpleflow.cpp(134): error C2653: 'traits'`

How did you compiled the optflow module of opencv ??

**Comment by LaurentBerger** [comment]
follow this instruction https://docs.opencv.org/master/d3/d52/tutorial_windows_install.html#tutorial_windows_gitbash_build (using good cmake generator)

**Comment by andreluizbarbieri** [comment]
I re-built all dependencies Again (wxWidgets, Qt, PLplot, VTK, OpenSceneGraph, OpenCV) totaling 26Gb !! And now all 'files'.lib built !

Again I will try build your project... Souhaitez-moi bonne chance!

**Comment by andreluizbarbieri** [comment]
I Built it !!!! 
 after Re-build and re-build everything and ADD additional library directory 

> D:\OpenSceneGraph\build\lib;
 D:\plplot\build\dll\Debug)

 and INPUT additional dependencies 

> OpenThreads.lib
OpenThreadsd.lib
osg.lib
osgAnimation.lib
osgd.lib
osgDB.lib
osgDBd.lib
osgFX.lib
osgFXd.lib
osgGA.lib
osgGAd.lib
osgManipulator.lib
osgParticle.lib
osgParticled.lib
osgPresentation.lib
osgShadow.lib
osgShadowd.lib
osgSim.lib
osgSimd.lib
osgTerrain.lib
osgTerraind.lib
osgText.lib
osgTextd.lib
osgUI.lib
osgUtil.lib
osgUtild.lib
osgViewer.lib
osgVolume.lib
osgVolumed.lib
osgWidget.lib
csirocsa.lib
mem.lib
null.lib
plplot.lib
plplotcxx.lib
plplotwxwidgets.lib
ps.lib
qsastime.lib
svg.lib
wxwidgets.lib
xfig.lib

**Comment by LaurentBerger** [comment]
Normally you don't need to add lib because cmake must do it.
