### ISSUE TITLE
Run it

### ISSUE THREAD

**Issue by andreluizbarbieri** [LaurentBerger/wxOpenCV#3]
The program run very well, it show Interface and few buttons/functions work. 
But when I click in Open and select a picture I get this error:

> onecoreuap\shell\windows.storage\filefldr.cpp(7769)\windows.storage.dll!759665FB: (caller: 759493B2) ReturnHr(20) tid(57cc) 80004005 Erro não especificado
O thread 0x6684 foi fechado com o código 1 (0x1).
onecoreuap\shell\windows.storage\filefldr.cpp(7769)\windows.storage.dll!759665FB: (caller: 759493B2) ReturnHr(21) tid(52c) 80004005 Erro não especificado
"wxOpenCVMain.exe" (Win32): Não carregado "C:\Windows\SysWOW64\msftedit.dll"
"wxOpenCVMain.exe" (Win32): Não carregado "C:\Windows\SysWOW64\xmllite.dll"
O thread 0x48a0 foi fechado com o código 0 (0x0).
"wxOpenCVMain.exe" (Win32): Não carregado "C:\Windows\SysWOW64\WMASF.DLL"
"wxOpenCVMain.exe" (Win32): Não carregado "C:\Windows\SysWOW64\mfperfhelper.dll"
"wxOpenCVMain.exe" (Win32): Não carregado "C:\Windows\SysWOW64\WMVCORE.DLL"
"wxOpenCVMain.exe" (Win32): Não carregado "C:\Windows\SysWOW64\audiodev.dll"
"wxOpenCVMain.exe" (Win32): Não carregado "C:\Windows\SysWOW64\wpdshext.dll"
D:\wxWidgets\include\wx/msw/private.h(809): 'UnregisterClass' failed with error 0x00000584 (a classe ainda tem janelas abertas.).
O thread 0x36c0 foi fechado com o código 1 (0x1).
Detected memory leaks!

and for other execution:

> onecoreuap\shell\windows.storage\filefldr.cpp(7769)\windows.storage.dll!759665FB: (caller: 759493B2) ReturnHr(21) tid(62c4) 80004005 Erro não especificado
shell\comdlg32\fileopensave.cpp(14301)\COMDLG32.dll!75E4FB33: (caller: 75E5ABCC) ReturnHr(1) tid(5bfc) 80004005 Erro não especificado
    CallContext:[\PickerModalLoop] 
"wxOpenCVMain.exe" (Win32): Não carregado "C:\Windows\SysWOW64\msftedit.dll"
onecoreuap\shell\windows.storage\regfldr.cpp(1240)\windows.storage.dll!75AB1192: (caller: 75942090) ReturnHr(22) tid(5bfc) 80004001 Não implementado
"wxOpenCVMain.exe" (Win32): Carregado "C:\Windows\SysWOW64\networkexplorer.dll". Não é possível localizar ou abrir o arquivo PDB.
"wxOpenCVMain.exe" (Win32): Não carregado "C:\Windows\SysWOW64\xmllite.dll"
O thread 0x51a4 foi fechado com o código 0 (0x0).
"wxOpenCVMain.exe" (Win32): Não carregado "C:\Windows\SysWOW64\WMASF.DLL"
"wxOpenCVMain.exe" (Win32): Não carregado "C:\Windows\SysWOW64\mfperfhelper.dll"
"wxOpenCVMain.exe" (Win32): Não carregado "C:\Windows\SysWOW64\WMVCORE.DLL"
"wxOpenCVMain.exe" (Win32): Não carregado "C:\Windows\SysWOW64\audiodev.dll"
"wxOpenCVMain.exe" (Win32): Não carregado "C:\Windows\SysWOW64\wpdshext.dll"
D:\wxWidgets\include\wx/msw/private.h(809): 'UnregisterClass' failed with error 0x00000584 (a classe ainda tem janelas abertas.).
O thread 0x5978 foi fechado com o código 1 (0x1).
Detected memory leaks!

**Comment by LaurentBerger** [comment]
I think you mixed some libs, debug and release  

Can you post cmakecache.txt?

**Comment by andreluizbarbieri** [comment]
[CMakeCache.txt](https://github.com/LaurentBerger/wxOpenCV/files/1513488/CMakeCache.txt)

![captura de tela 1](https://user-images.githubusercontent.com/14797086/33372390-ff1948d8-d4e4-11e7-980c-16947e96113a.png)
Look this error into Log window:
I found this ref. in 3 files: FenetrePrincipale.cpp ImageStat.cpp ControleCamera.cpp
but the file wxocv.bmp haven't in the project folder. --- I try put a file with name 'wxocv.bmp' (error disappear) but it still crash (other cause).

**Comment by andreluizbarbieri** [comment]
All buttons work very well, Reset Windows menu works, Convolution filter interact with Blue matrix, but 'Open File' still cause crash... (What is your Windows OS ?)

I try again debug it:

> FTH: (12984): *** Fault tolerant heap shim applied to current process. This is usually due to previous crashes. ***
onecore\com\combase\inc\comcataloghelpers.hpp(67)\combase.dll!75E39E42: (caller: 75E386C7) ReturnHr(1) tid(24c8) 80004002 Não há suporte para esta interface
mincore\com\oleaut32\dispatch\ups.cpp(2125)\OLEAUT32.dll!74BA6CEF: (caller: 74BA688E) ReturnHr(1) tid(d9c) 8002801D Biblioteca não registrada.
onecoreuap\shell\windows.storage\regfldr.cpp(1240)\windows.storage.dll!77A61192: (caller: 778F2090) ReturnHr(1) tid(d9c) 80004001 Não implementado
Exceção gerada em 0x76109942 (KernelBase.dll) em wxOpenCVMain.exe: 0x000006BA: O servidor RPC não está disponível.

> onecoreuap\shell\windows.storage\kfapi\folderpathidlistcache.cpp(208)\windows.storage.dll!779116F5: (caller: 7790FC0C) LogHr(1) tid(d9c) 80070002 O sistema não pode encontrar o arquivo especificado.
onecoreuap\shell\windows.storage\kfapi\folderpathidlistcache.cpp(208)\windows.storage.dll!779116F5: (caller: 7790FC0C) LogHr(2) tid(d9c) 80070002 O sistema não pode encontrar o arquivo especificado.

> onecoreuap\shell\ext\thumbnailcache\lib\thumbcacheapi.cpp(288)\thumbcache.dll!50162C01: (caller: 50152CE1) ReturnHr(1) tid(d9c) 80004005 Erro não especificado
onecoreuap\shell\ext\thumbnailcache\lib\thumbcacheapi.cpp(162)\thumbcache.dll!5017145E: (caller: 77868087) ReturnHr(2) tid(d9c) 80004005 Erro não especificado
onecoreuap\shell\windows.storage\kfapi\folderpathidlistcache.cpp(208)\windows.storage.dll!779116F5: (caller: 7790FC0C) LogHr(3) tid(d9c) 80070002 O sistema não pode encontrar o arquivo especificado.

**Comment by LaurentBerger** [comment]
Are you in 32bits ? CMAKE_STATIC_LINKER_FLAGS:STRING=/machine:X86 (in 64 bits should be x64)

You built opencv in 32 bits : CMAKE_GENERATOR:INTERNAL=Visual Studio 15 2017.

Why don't you install path for openscenegraph 

![sans titre](https://user-images.githubusercontent.com/3591626/33376189-f88bad62-d50c-11e7-87b9-d264ecc9ad5a.png)

**Comment by andreluizbarbieri** [comment]
I built all dependencies (wxWidgets, Qt, PLplot, VTK, OpenSceneGraph, OpenCV) in 32bits.
Should I delete and try re-built all in 64bits?

**Comment by LaurentBerger** [comment]
No but I think problem is you add yourself lib in VS project. Make a copy of this folder and try to use right path in cmake gui. Then all libs will be add by cmake in vs solution.

Long time ago it worked in 32 bits I don't think it is a problem. If you have a 64 bits system you should rebuild everything in 64 bits. Cmake generator is Visual Studio 15 2017 Win64.

**Comment by andreluizbarbieri** [comment]
But the Cmake-Gui with your Cmakelists.txt don't find PLplot libs even if I put the folder path

**Comment by LaurentBerger** [comment]
Have you install plplot ?

**Comment by andreluizbarbieri** [comment]
Yes. Look:
![capturar_0](https://user-images.githubusercontent.com/14797086/33388793-0a1da98a-d518-11e7-8b72-ffc4923d74e6.PNG)
![capturar](https://user-images.githubusercontent.com/14797086/33388795-0bf612c4-d518-11e7-8eab-c408518f4dfd.PNG)
![capturar2](https://user-images.githubusercontent.com/14797086/33388852-3ccf776e-d518-11e7-9c3f-559fce6aa027.PNG)

and after that I click in Configure the Cmake-gui remove the PATH

![capturar3](https://user-images.githubusercontent.com/14797086/33388803-0e5cf0f0-d518-11e7-9ab0-b84ede72eeca.PNG)

**Comment by LaurentBerger** [comment]
No that's not install folder , It is build folder. Install folder is :
![image](https://user-images.githubusercontent.com/3591626/33388913-9550891e-d531-11e7-8767-13ddb8c48259.png)

Opencv install is : 
![image](https://user-images.githubusercontent.com/3591626/33388952-b61cd17a-d531-11e7-9f45-cc45a1932e84.png)

and openscenegraph
![image](https://user-images.githubusercontent.com/3591626/33388993-d38fe4d6-d531-11e7-917c-de6ddc77aa34.png)

**Comment by andreluizbarbieri** [comment]
This is correct?
![capturar](https://user-images.githubusercontent.com/14797086/33389337-ae2d4c46-d519-11e7-8978-9be091986449.PNG)
But still Cmake haven't the "PLplotConfig.cmake" file... Can you upload for me, please?

> CMake Error at CMakeLists.txt:25 (find_package):
  By not providing "FindPLplot.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PLplot", but
  CMake did not find one.
  Could not find a package configuration file provided by "PLplot" with any
  of the following names:
    PLplotConfig.cmake
    plplot-config.cmake
  Add the installation prefix of "PLplot" to CMAKE_PREFIX_PATH or set
  "PLplot_DIR" to a directory containing one of the above files.  If "PLplot"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by LaurentBerger** [comment]
Have you set plplot_dir to d:/plplot/lib/cmake/plplot ? (cmake needs some help)

**Comment by andreluizbarbieri** [comment]
cmak-gui Works with "d:/plplot/lib/cmake/plplot" ! Thanks

> OPENCV = D:/opencv/build;D:/opencv/include;D:/opencv/include/opencv;D:/opencv/modules/core/include;D:/opencv/modules/flann/include;D:/opencv/modules/imgproc/include;D:/opencv/modules/ml/include;D:/opencv/modules/objdetect/include;D:/opencv_contrib/modules/phase_unwrapping/include;D:/opencv/modules/photo/include;D:/opencv_contrib/modules/plot/include;D:/opencv_contrib/modules/reg/include;D:/opencv_contrib/modules/surface_matching/include;D:/opencv/modules/video/include;D:/opencv/modules/viz/include;D:/opencv_contrib/modules/xphoto/include;D:/opencv_contrib/modules/bgsegm/include;D:/opencv/modules/dnn/include;D:/opencv_contrib/modules/fuzzy/include;D:/opencv_contrib/modules/img_hash/include;D:/opencv/modules/imgcodecs/include;D:/opencv/modules/shape/include;D:/opencv/modules/videoio/include;D:/opencv_contrib/modules/xobjdetect/include;D:/opencv/modules/highgui/include;D:/opencv/modules/superres/include;D:/opencv/modules/ts/include;D:/opencv_contrib/modules/bioinspired/include;D:/opencv_contrib/modules/dpm/include;D:/opencv/modules/features2d/include;D:/opencv_contrib/modules/line_descriptor/include;D:/opencv_contrib/modules/saliency/include;D:/opencv_contrib/modules/text/include;D:/opencv/modules/calib3d/include;D:/opencv_contrib/modules/ccalib/include;D:/opencv_contrib/modules/datasets/include;D:/opencv_contrib/modules/rgbd/include;D:/opencv_contrib/modules/stereo/include;D:/opencv_contrib/modules/structured_light/include;D:/opencv_contrib/modules/tracking/include;D:/opencv/modules/videostab/include;D:/opencv_contrib/modules/xfeatures2d/include;D:/opencv_contrib/modules/ximgproc/include;D:/opencv_contrib/modules/aruco/include;D:/opencv_contrib/modules/face/include;D:/opencv_contrib/modules/optflow/include;D:/opencv/modules/stitching/include
 PATH0 
 PATH1  
 PATH3 d:/plplot/lib/cmake/plplot
 PATH4 
 PATH0 plplot;plplotcxx;D:/wxWidgets/lib/vc_lib/wxbase31ud.lib;D:/wxWidgets/lib/vc_lib/wxmsw31ud_core.lib;D:/wxWidgets/lib/vc_lib/wxpngd.lib;D:/wxWidgets/lib/vc_lib/wxtiffd.lib;D:/wxWidgets/lib/vc_lib/wxjpegd.lib;D:/wxWidgets/lib/vc_lib/wxzlibd.lib;D:/wxWidgets/lib/vc_lib/wxregexud.lib;D:/wxWidgets/lib/vc_lib/wxexpatd.lib;winmm;comctl32;oleacc;rpcrt4;shlwapi;version;wsock32
 PATH1  
 PATH3 csirocsa;qsastime
 PATH4 plplot
WINDOWS
D:/wxWidgets/lib/vc_lib
Configuring done

**Comment by andreluizbarbieri** [comment]
Please, help me fix it below (I Think that is the wxWidgets libs with link errors)
![capturar](https://user-images.githubusercontent.com/14797086/33391465-44d0a2b4-d520-11e7-9cad-9aa4d1970107.PNG)

**Comment by LaurentBerger** [comment]
Ok there is a bug in plplot I think plplotwxwidgets.lib is not in lib list (check it).
Add d:/plplot/lib/plplotwxwidgets.lib to entry (linker list) in project properties

**Comment by andreluizbarbieri** [comment]
It's correct! Now build with no errors... And plus, the wxOpenCV is working and it open file without crash! 

> 2>Gerando Código...
2>LINK : warning LNK4075: ignorando '/INCREMENTAL' devido a especificação '/FORCE'
2>wxOpenCVMain.vcxproj -> C:\Users\andre\Source\repos\wxOpenCV\build\wxOpenCVMain\Debug\wxOpenCVMain.exe
2>Projeto de compilação pronto "wxOpenCVMain.vcxproj".
3>------ Recompilação total ignorada Projeto: ALL_BUILD, Configuração: Debug Win32 ------
3>Não há projeto selecionado para compilar nesta configuração de solução 
========== Recompilar Tudo: 2 com êxito, 0 com falha, 1 ignorados ==========

Then The Gold Tip is : Build everything with INSTALL Project,  set PLPLOT_DIR = "plplot/lib/cmake/plplot" and ADD for INPUT in LINKER the "plplot/lib/plplotwxwidgets.lib"

**Comment by andreluizbarbieri** [comment]
Merci pour tout, tu étais un grand ami.

**Comment by andreluizbarbieri** [comment]
I see that you merge all dll's into executable for your release in your site... Did you use the ILmerge.exe? 
I would like see the command line for merge dll's.

**Comment by LaurentBerger** [comment]
No all libs built in static

**Comment by andreluizbarbieri** [comment]
Should I build wxwidgets plplot osg opencv without dynamic lib (static)?

**Comment by LaurentBerger** [comment]
Yes if you want only exe. but opencv_ffmpeg is always a dll

**Comment by andreluizbarbieri** [comment]
Should I set in VSproject for all (wxwidgets plplot osg opencv)
 as "static library" project config,  (--it did not help)
 or I set in Cmake-gui for uncheck SHARED_LIB ?

Or should I set for "/MT" without DLL ? 
but with this compilation mode I need set more and more .lib in dependencies... 
Do you have the list of all .lib for INPUT box when /MT is set ?

**Comment by andreluizbarbieri** [comment]
please, answer me. Je promets de ne plus te déranger.

> `wxIUA.cpp`

> `Generating Code...`

> `wxmsw31ud_core.lib(window.obj) : Error LNK2038
mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in AffichageNouvelleImage.obj`

even after build VTK OSG PLplot wxWidget openCV as "Static Library" configuration, and try build wxOpenCV with /MTd compilation mode.

What do I do for build the executable with static libs? or How build the others Libs (wxwidgets plplot osg opencv) as Static?


I think that the wxwidget need of a patch for build static lib? https://forums.wxwidgets.org/viewtopic.php?t=40156 
or just select all project in wxWidget to change for /MTd https://sites.google.com/site/opensourceconstriubtions/ettl-martin-1/tutorials/how-to-compile-the-wxwidgets-into-static-library --but after build I try run it then show runtime error...

the question is: What are the step for build the executable without need of DLL?

**Comment by LaurentBerger** [comment]
I have test in static  using vs2017 and results are [here](http://perso.univ-lemans.fr/~berger/wxOpenCV/PHP/download.php). Can you test it?
If it works for you you can try :: 
first you don't need to change anything in wxwidgets no patch are needed using last version of wxwidgets (update using git pull): message is too old forget it

You have to check that all projects (osg plplot wxwidgets opencv and wxopencv use  generation code flag /MD for release and MDd for debug). For opencv you need to uncheck BUILD_WITH_STATIC_CRT)
You have to select in wxopencv cmake  wxWidgets-3.1.0/lib/vc_x64_lib : 
![image](https://user-images.githubusercontent.com/3591626/33526209-0029a018-d83e-11e7-98ea-2ab564055d4a.png)

**Comment by andreluizgit** [comment]
Thanks for answer. I will try in this night...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by andreluizbarbieri** [comment]
First: the download link works ! (but after open image it crash) but I fixed
![capturar](https://user-images.githubusercontent.com/14797086/33529723-05fc5bb6-d85c-11e7-9840-7a94d08607e6.PNG)
after that I add your 8 files it works !!!

Second: after set your tips, the VS2107 re-run cmake:

> `1>Checking Build System
1>CMake is re-running because C:/Users/andre/Source/repos/wxOpenCV/build/CMakeFiles/generate.stamp is out-of-date.
1>  the file 'D:/opencv/build/OpenCVConfig.cmake'
1>  is newer than 'C:/Users/andre/Source/repos/wxOpenCV/build/CMakeFiles/generate.stamp.depend'
1>  result='-1'
1>-- Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.17046.
1>OPENCV = D:/opencv/build;D:/opencv/include;...;D:/opencv/modules/stitching/include
1> PATH0
1> PATH1
1> PATH3 d:/plplot/lib/cmake/plplot
1> PATH4
1> PATH0 plplot;plplotcxx;D:/wxWidgets/lib/vc_lib/wxbase31ud.lib;D:/wxWidgets/lib/vc_lib/wxmsw31ud_core.lib;D:/wxWidgets/lib/vc_lib/wxpngd.lib;D:/wxWidgets/lib/vc_lib/wxtiffd.lib;D:/wxWidgets/lib/vc_lib/wxjpegd.lib;D:/wxWidgets/lib/vc_lib/wxzlibd.lib;D:/wxWidgets/lib/vc_lib/wxregexud.lib;D:/wxWidgets/lib/vc_lib/wxexpatd.lib;winmm;comctl32;oleacc;rpcrt4;shlwapi;version;wsock32
1> PATH1
1> PATH3 csirocsa;qsastime
1> PATH4 plplot
1>-- WINDOWS
1>-- D:/wxWidgets/lib/vc_lib
1>-- Configuring done
1>-- Generating done`

Third: I get LNK errors:

> `2>wxIUA.cpp`
`2>Gerando Código...`
`2>LINK : warning LNK4075: ignorando '/INCREMENTAL' devido a especificação '/FORCE'`
`2>libjpegd.lib(jcparam.obj) : warning LNK4006: _jpeg_set_defaults já definido no wxjpegd.lib(jcparam.obj); segunda definição ignorada`
`2>libjpegd.lib(jcparam.obj) : warning LNK4006: _jpeg_set_colorspace já definido no wxjpegd.lib(jcparam.obj); segunda definição ignorada
2>libjpegd.lib(jcparam.obj) : warning LNK4006: _jpeg_default_colorspace já definido no wxjpegd.lib(jcparam.obj); segunda definição ignorada
2>libjpegd.lib(jcparam.obj) : warning LNK4006: _jpeg_set_quality já definido no wxjpegd.lib(jcparam.obj); segunda definição ignorada
2>libjpegd.lib(jcparam.obj) : warning LNK4006: _jpeg_set_linear_quality já definido no wxjpegd.lib(jcparam.obj); segunda definição ignorada
2>libjpegd.lib(jcparam.obj) : warning LNK4006: _jpeg_add_quant_table já definido no wxjpegd.lib(jcparam.obj); segunda definição ignorada
2>libjpegd.lib(jcparam.obj) : warning LNK4006: _jpeg_quality_scaling já definido no wxjpegd.lib(jcparam.obj); segunda definição ignorada
2>libjpegd.lib(jcparam.obj) : warning LNK4006: _jpeg_simple_progression já definido no wxjpegd.lib(jcparam.obj); segunda definição ignorada`

> `2>VideoCourbe.obj : error LNK2001: símbolos externos indefinidos "public: __thiscall wxPLplotstream::wxPLplotstream(void)" (??0wxPLplotstream@@QAE@XZ)`
`2>FenetreCoupe.obj : error LNK2001: símbolos externos indefinidos "public: __thiscall wxPLplotstream::wxPLplotstream(void)" (??0wxPLplotstream@@QAE@XZ)`
`2>FenetreDistribradiale.obj : error LNK2001: símbolos externos indefinidos "public: __thiscall wxPLplotstream::wxPLplotstream(void)" (??0wxPLplotstream@@QAE@XZ)
2>FenetreFocus.obj : error LNK2001: símbolos externos indefinidos "public: __thiscall wxPLplotstream::wxPLplotstream(void)" (??0wxPLplotstream@@QAE@XZ)
2>FenetreHistogramme.obj : error LNK2001: símbolos externos indefinidos "public: __thiscall wxPLplotstream::wxPLplotstream(void)" (??0wxPLplotstream@@QAE@XZ)`

I think this is no set INPUT then I add "plplot\lib\plplotwxwidgets.lib" (cmake runned again)

**Comment by LaurentBerger** [comment]
Oops! it's ok now

**Comment by andreluizbarbieri** [comment]
Then now I can build static mode !!!  

> opencv (BUILD_WITH_STATIC_CRT=OFF and SHARED_LIBS=OFF) and 
> wxOpenCV (add plplotwxwidgets.lib in INPUT of Linker).

But I get white window (without image) after open a image...

![capturar](https://user-images.githubusercontent.com/14797086/33529779-6db04060-d85c-11e7-85f6-0047c8d921de.PNG)

**Comment by LaurentBerger** [comment]
with download version and your version? Click in stat you will be able to read image size

**Comment by andreluizbarbieri** [comment]
your version or my version? my local (your) version has white image (but your download version is ok)

![capturar](https://user-images.githubusercontent.com/14797086/33531065-61656796-d86f-11e7-9fac-92a50e088172.PNG)


You have ask me: "wxwidgets no patch are needed using last version of wxwidgets" and I can say that I download of here https://www.wxwidgets.org/downloads/ the "Windows zip version of Source Code"
-- can be this the strange behavior... already downloading of https://github.com/wxWidgets/wxWidgets
However I can't build the git wxWidgets version:

> `Don't exist wxWidgets\lib\vc_lib\wxbase31ud.lib`

> `'zconf.h': No such file or directory`

> `1>wxIUA.cpp
1>Gerando Código...
1>LINK : warning LNK4075: ignorando '/INCREMENTAL' devido a especificação '/FORCE'
1>LINK : fatal error LNK1181: não foi possível abrir o arquivo de entrada 'D:\wxWidgets\lib\vc_lib\wxbase31ud.lib'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(651,5): error MSB6006: "link.exe" foi encerrado com o código 1181.
1>Projeto de compilação pronto "wxOpenCVMain.vcxproj" -- FALHA.`

That is, I can't build zlib project -> I can't build wxbase -> I can't build wxWidgets :
 because `'zconf.h': No such file or directory`

I fixed:
![capturar](https://user-images.githubusercontent.com/14797086/33532242-0b4a07ee-d87f-11e7-93fc-d8ed273ee86c.PNG)
Create the zconf.h why somebody exclude it of project!

**Comment by andreluizbarbieri** [comment]
Now with wxWidgets of git + zconf.h = Everything working! Thanks very much!
Merci beaucoup, et désolé de vous déranger tellement. Tu es un bon ami!

**Comment by LaurentBerger** [comment]
About wxwidgets using you have to enter command git submodule update --init

**Comment by andreluizbarbieri** [comment]
Thanks a lot.

I see that after build with No SHARED_LIBS (I build all dependencies as OSG PLplot and OpenCV) I can no more need .DLL files (It's Goood) but there are still Some that I need put in project folder:

![capturar](https://user-images.githubusercontent.com/14797086/33716529-b5938e76-db3d-11e7-826a-edca8e6f2c68.PNG)

Do you know how configure OSG for no need DLL files? 
I already Unchecked DYNAMIC_OPENSCENEGRAPH and DYNAMIC_OPENTHREADS

**Comment by LaurentBerger** [comment]
It should be good. Have you delete cmakecahe.txt?

**Comment by andreluizbarbieri** [comment]
I didn't delete... I just configure, generate and open project Again
Then I will delete it then rebuild...
