### ISSUE TITLE
 Low RMS value when calibrating single camera, while high RMS value in stereoCalibrate

### ISSUE THREAD

**Issue by ahyow** [LaurentBerger/wxOpenCV#6]
Hi, i saw you have the issue of 
Low RMS value when calibrating single camera, while high RMS value in stereoCalibrate which posted in the forum https://answers.opencv.org/question/173249/low-rms-value-when-calibrating-single-camera-while-high-rms-value-in-stereocalibrate/

I would like to ask if you found the answer because i have the same question

**Comment by LaurentBerger** [comment]
Sorry for delay but I'm not author issue
